In [1]:
import torch

In [4]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape

torch.Size([12])

In [9]:
x.reshape(3, -1) # 使用 -1 进行省略计算

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
x.numel() # num_elements 元素的总数

12

In [10]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [11]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4)) 
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]) 
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [12]:
# 使用切片赋值，避免多余的内存开销，numpy 也是一样的原理
# X += Y 也可以避免内存开销
Z = torch.zeros_like(Y) 
print('id(Z):', id(Z)) 
Z[:] = X + Y 
print('id(Z):', id(Z))

id(Z): 140517752776160
id(Z): 140517752776160


In [18]:
import numpy as np

Z = np.zeros_like(Y) 
print('id(Z):', id(Z)) 
# Z[:] = X + Y 
Z += Z
print('id(Z):', id(Z))

id(Z): 140517752752816
id(Z): 140517752752816
